server:
  port: 8084

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/BankManagementSystem
#    url: jdbc:postgresql://localhost:5432/BankManagementSystem
    username: postgres
    password: YOUR_PASSWORD
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "YOUR_SECRET_KEY"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/   # use discovery-service instead of localhost
    register-with-eureka: true
    fetch-registry: true

security:
  jwt:
    issuer: bank-auth
    access-token-ttl-min: 120
    refresh-token-ttl-days: 14
    secret: "a3a9b7cbe55a42fd83cf1b7df3e9e7f178fd3a07b2d6f4cbb31f2d47ac982bd0"
